---
- name: A playbook showing the file module
  hosts: planetexpress

  tasks:
   - name: Create directory where Space Station documents will reside
     become_user: root
     become: true
     file:
        # the var "fileuser" is a host variable
        path: "~/station_docs/"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

   - name: "Create directory where Space Station documents will reside"
     copy:
        # the var "fileuser" is a host variablen
        # ansible_date_time.date is defined by gather_facts
        dest: "~/station_docs/navdata-{{ ansible_date_time.date }}.txt"
        content: "Earth\nMars\nSaturn\nEuropa"
