---
- name: Network Playbook
  hosts: allvendors
  gather_facts: yes

  vars_files:
          - ~/netcreds.yml

  tasks:
          - name: Display ansible_facts
            debug:
                    var: ansible_facts
            no_log: true

          - name: Gather EOS facts
            eos_facts:
                    gather_subset:
                            - all
                            #- !hardware
                            ###register: results

          - name: Display gathered facts
            debug:
                    #var: results
                    var: ansible_facts

          - name: log a credential
            debug:
                    var: ansible_ssh_pass
            no_log: yes
