# cat linux_jenkins.yml
---
- name: Install Jenkins
  hosts: localhost
  gather_facts: no
  become: yes

  # Manual Jenkins install instructions can be found @
  # Debian:
  # http://pkg.jenkins-ci.org/debian-stable/
  # Redhat:
  # http://pkg.jenkins-ci.org/redhat-stable/

  vars:
          jenkins_version: "2.204.5"  # 2.204.5 released on 2020/03/07
          jenkins_pkg_url: "http://pkg.jenkins-ci.org/debian-stable/binary"
          jenkins_package_state: present # change to absent to remove
          jenkins_http_port: 8087  # port to run jenkins on
          jenkins_init_file: /etc/default/jenkins # contains global settings for jenkins

  tasks:
        # Jenkins requires Java
        # The best way to install Java on linux is via open-java
        # in apt repo this is called default-jdk
        - name: Ensure dependencies are installed
          apt:
            name:
              - default-jdk
              - curl
              - apt-transport-https
              - gnupg
            state: present

        # add Jenkins repo key per 
        # http://pkg.jenkins-ci.org/debian-stable/
        - name: Add Jenkins apt repository key
          apt_key:
            url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
            state: present

        - name: Add Jenkins apt repository
          apt_repository:
            repo: deb https://pkg.jenkins.io/debian-stable binary/
            state: present
            update_cache: true
          when: jenkins_repo_url | default(false)

        # the versions of jenkins are available via
        # http://pkg.jenkins-ci.org/debian-stable/
        - name: Download specific Jenkins version
          get_url:
            # http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_2.204.5_all.deb
            url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
            dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
          when: jenkins_version is defined

          #        - name: Check if we downloaded a specific version of Jenkins.
          #          stat:
          #            path: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
          #          register: specific_version
          #          when: jenkins_version is defined

        - name: Install our specific version of Jenkins
          apt:
            deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
            state: "{{ jenkins_package_state }}"
          when: jenkins_version is defined
          #notify: configure default users

        #- name: Ensure Jenkins is installed
        #  apt:
        #    name: jenkins
        #    state: "{{ jenkins_package_state }}"
        #  #notify: configure default users
       
        # edit the port that Jenkins runs on by editing
        # the Jenkins configuration file 
        - name: Set the port on which Jenkins runs
          lineinfile:
            backrefs: true
            dest: "{{ jenkins_init_file }}"
            regexp: '^HTTP_PORT='
            line: 'HTTP_PORT={{ jenkins_http_port }}'
          register: jenkins_http_config
          notify: restart jenkins

        # display the initial Admin password on the screen
        - name: Get init password Jenkins
          shell: cat /var/lib/jenkins/secrets/initialAdminPassword
          changed_when: false
          register: result
    
        - name: Print init password Jenkins
          debug:
            var: result.stdout


  handlers:
        
        - name: restart jenkins
          service:
            name: jenkins
            state: restarted
        
            #        - name: configure default users
            #          template:
            #                  src: basic-security.groovy.j2
            #                  dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
            #                  owner: "{{ jenkins_process_user }}"
            #                  group: "{{ jenkins_process_group }}"
            #                  mode: 0775
            #          register: jenkins_users_config
