---
- name: Playbook that sends HTTP GET to target URI
  hosts: localhost
 
  vars: 
    uritolookup: "http://api.open-notify.org/astros.json"
  
  tasks:
  - name: Lookup api with uri module
    uri:
      url: "http://api.open-notify.org/astros.json"
      method: GET
    register: results    # save the JSON sent back by our script
  
  - name: Print out the 'results'
    debug:
      var: results
